/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AMN1oTPiRNi
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Landing() {
  return (
    (<main
      key="1"
      className="flex flex-col items-center justify-center text-black min-h-screen p-4 bg-[#f5f5f5]">
      <div className="w-full max-w-2xl mx-auto space-y-6">
        <br></br>
        <div className="p-6 bg-white rounded-lg shadow-md space-y-4">
          <h1 className="text-3xl font-bold text-center">Github 👉 Medium Article</h1>
          <h2 className="text-xl text-center">Just paste your public repo link below to generate a dev guide</h2>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label className="text-lg" htmlFor="github-link">
               GitHub Repo URL
              </Label>
              <Input
                className="p-2 text-lg"
                id="github-link"
                placeholder="https://github.com/username/repo"
                required />
            </div>
            <Button className="w-full p-2 text-lg bg-black text-white rounded" type="submit">
              Generate Now
            </Button>
          </div>
        </div>
        <div className="p-4 bg-white rounded-lg shadow-md space-y-4">
          <h1 className="text-2xl font-semibold text-center">Advertisement</h1>
        </div>
        <div className="p-6 bg-white rounded-lg shadow-md space-y-4">
          <h1 className="text-3xl font-bold text-center">Watch the Magic Happen</h1>
          <h2 className="text-xl text-center">Check out the live generation steps of your blog post below.</h2>
          <div className="space-y-4">
            <div className="flex items-center space-x-4">
              <CheckIcon className="w-6 h-6 text-green-500" />
              <p className="text-lg">Cloning the repository...</p>
            </div>
            <div className="flex items-center space-x-4">
              <CheckIcon className="w-6 h-6 text-green-500" />
              <p className="text-lg">Reading the files...</p>
            </div>
            <div className="flex items-center space-x-4">
              <CheckIcon className="w-6 h-6 text-green-500" />
              <p className="text-lg">Generating the blog post...</p>
            </div>
            <div className="flex items-center space-x-4">
              <CheckIcon className="w-6 h-6 text-green-500" />
              <p className="text-lg">Blog post generated successfully!</p>
            </div>
          </div>
        </div>
        <div className="p-6 bg-white rounded-lg shadow-md space-y-4">
          <h1 className="text-3xl font-bold text-center">Copy to Medium</h1>
          <h2 className="text-xl text-center">Click the button to copy the link to your generated blog post.</h2>
          <div className="space-y-4">
            <div className="flex items-center justify-between space-x-4">
              <Input
                className="p-2 text-lg flex-grow"
                id="blog-link"
                readOnly
                value="/blog-post" />
              <Button className="p-2 text-lg bg-black text-white rounded" type="button">
                Copy and Show Success
              </Button>
            </div>
          </div>
        </div>
      </div>
    </main>)
  );
}


function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>)
  );
}
